server:
  port: 8080


spring:
  application:
    name: seo_agent

#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: llama3.2
  ai:
    anthropic:
      api-key: API_KEY
      chat:
        options:
          model: claude-sonnet-4-0
